--List all appointments with patient name, doctor name, specialization, and diagnosis.
SELECT doctor.name, COUNT(appointment.appointment_id) AS total_appointments
FROM doctor
JOIN appointment ON doctor.doctor_id = appointment.doctor_id
GROUP BY doctor.name;
--Generate a billing report for each patient including doctor fee
SELECT 
    p.name AS patient_name,
    d.name AS doctor_name,
    d.fees AS consultation_fee,
    a.date AS appointment_date
FROM appointment a
JOIN patient p ON a.patient_id = p.patient_id
JOIN doctor d ON a.doctor_id = d.doctor_id
ORDER BY a.date DESC;
--Total revenue generated by each doctor
SELECT 
    d.name AS doctor_name,
    d.specialization,
    d.fees,
    COUNT(a.appointment_id) AS appointments,
    (COUNT(a.appointment_id) * d.fees) AS total_revenue
FROM doctor d
JOIN appointment a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id
ORDER BY total_revenue DESC;
--Get a list of all diagnoses along with patient's name, doctor’s name, and appointment date
SELECT diagnosis.diagnosis_id, patient.name AS patient_name, doctor.name AS doctor_name, appointment.date, diagnosis.diagnosis, diagnosis.prescription
FROM diagnosis
JOIN appointment ON diagnosis.appointment_id = appointment.appointment_id
JOIN patient ON appointment.patient_id = patient.patient_id
JOIN doctor ON appointment.doctor_id = doctor.doctor_id;
--To extract a specific appointment using doctor name and time
SELECT 
    a.appointment_id,
    d.name AS doctor_name,
    p.name AS patient_name,
    a.date,
    a.start_time,
    a.end_time,
    a.status,
    a.concerns,
    a.symptoms
FROM appointment a
JOIN doctor d ON a.doctor_id = d.doctor_id
JOIN patient p ON a.patient_id = p.patient_id
WHERE d.name = 'Dr. Tia'
  AND a.date = '2024-04-10'
  AND a.start_time = '09:00';
--Show medical history and diagnosis details for each patient
SELECT 
    patient.name AS patient_name,
    medical_history.date AS history_date,
    medical_history.conditions,
    medical_history.surgeries,
    diagnosis.diagnosis,
    diagnosis.prescription
FROM patient
JOIN medical_history ON patient.patient_id = medical_history.patient_id
JOIN appointment ON patient.patient_id = appointment.patient_id
JOIN diagnosis ON appointment.appointment_id = diagnosis.appointment_id;
--Show patients who were diagnosed with a specific condition (Migraine) and who their doctor was
SELECT 
    patient.name AS patient_name,
    doctor.name AS doctor_name,
    diagnosis.diagnosis,
    diagnosis.prescription,
    appointment.date
FROM diagnosis
JOIN appointment ON diagnosis.appointment_id = appointment.appointment_id
JOIN patient ON appointment.patient_id = patient.patient_id
JOIN doctor ON appointment.doctor_id = doctor.doctor_id
WHERE diagnosis.diagnosis ILIKE '%Migraine%';
--List of patients and how many appointments they’ve had with each doctor.
SELECT 
    p.name AS patient_name,
    d.name AS doctor_name,
    COUNT(a.appointment_id) AS total_appointments
FROM appointment a
JOIN patient p ON a.patient_id = p.patient_id
JOIN doctor d ON a.doctor_id = d.doctor_id
GROUP BY p.name, d.name
ORDER BY p.name, total_appointments DESC;
--Average number if appointments per day
SELECT 
  date,
  COUNT(*) AS total_appointments,
  ROUND(COUNT(*)::numeric / COUNT(DISTINCT date), 2) AS average_per_day
FROM appointment
GROUP BY date
ORDER BY date;
--Total number of patients treated per doctor
SELECT 
  d.name AS doctor_name,
  COUNT(DISTINCT pv.patient) AS unique_patients
FROM doctor d
JOIN diagnose dg ON d.email = dg.doctor
JOIN patient_visits pv ON dg.appt = pv.appt
GROUP BY d.name
ORDER BY unique_patients DESC;
--Most Common diseases in Medical_History
SELECT 
  conditions,
  COUNT(*) AS count
FROM medical_history
GROUP BY conditions
ORDER BY count DESC
LIMIT 3;
--List all appointments for a specific doctor. 
SELECT * FROM appointment WHERE doctor_id = (SELECT doctor_id FROM doctor WHERE name = 'Dr. Tia'); 
--Get the diagnoses for all patients who were prescribed 'Amlodipine'.
SELECT diagnosis, prescription FROM diagnosis WHERE appointment_id IN (SELECT appointment_id FROM appointment WHERE concerns LIKE '%Amlodipine%'); 
--Show all doctor schedules for a specific day. 
SELECT * FROM doctor_schedule WHERE day = 'Monday'; 
--Find all patients who have undergone a specific surgery . 
SELECT name FROM patient WHERE patient_id IN (SELECT patient_id FROM medical_history WHERE surgeries LIKE '%Appendectomy%'); 
--What is the diagnosis and prescription for a specific appointment ? 
SELECT diagnosis, prescription FROM diagnosis WHERE appointment_id = 2; 
--List all doctors with their email addresses. 
SELECT name, email FROM doctor; 
--Find the patient with the most recent medical history. 
SELECT * FROM medical_history WHERE date = (SELECT MAX(date) FROM medical_history); 
--Get the list of all appointments that are in 'Scheduled' status. 
SELECT * FROM appointment WHERE status = 'Scheduled';
--Count number of appointments per doctor
SELECT doctor.name, COUNT(appointment.appointment_id) AS total_appointments FROM doctor JOIN appointment ON doctor.doctor_id = appointment.doctor_id GROUP BY doctor.name ORDER BY total_appointments DESC;
